### ISSUE TITLE
Adding support for newest Cold Sweat version

### ISSUE THREAD

**Issue by squarzyy** [Viola-Siemens/Freeze-It-And-Heat-It#17]
Can we add support for current Coldsweat version: https://www.curseforge.com/minecraft/mc-mods/cold-sweat/files/5520717

**Comment by Viola-Siemens** [comment]
I used to support beta Cold Sweat versions before and turn out that the author of CS changes its package name and api frequently (eg. package name from `dev.momostudios.coldsweat` in beta to `com.momosoftworks.coldsweat` in release), which wasted me a lot of time to support all different versions by releasing new files. That's why I said I'd only like to support the latest release.
However, I'll think it over since I've receive a lot comments about beta version support. Thanks for your advice again.

**Comment by squarzyy** [comment]
Thank you for your reply,  my apologies for this advice. If possible in the next update, I think a new mechanism that would make the Mod better is to be able to preserve food in a closed room conditioned by a fan by Mod Create, this is actually the mechanism of this Mod https://www.curseforge.com/minecraft/mc-mods/freeze-create, it would be great if this mechanism could work with your Mod since both have different rotting mechanisms. Thank you again

**Comment by Viola-Siemens** [comment]
Nice idea. Thanks for your suggestion.

**Comment by Viola-Siemens** [comment]
version 1.2.7/2.2.5/3.1.1 will be released soon to fix this.
